version: '2.1'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow




    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - FERNET_KEY=WtcAFuSyNAeU3tMz5panc0M7gvwNP1tnej4hgo5Ysms=
            - EXECUTOR=Sequential
        volumes:
            - ./airflow/dags:/usr/local/airflow/dags
            - ./airflow/sql_templates:/usr/local/airflow/sql_templates
            # Uncomment to include custom plugins
            # - ./plugins:/usr/local/airflow/plugins
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    superset:
        image: amancevice/superset:latest
        ports:
            - "8088:8088"
               
            